#!/bin/ash

# Includes
. ./constants
. ./utils

# common functions

# Returns a line with line number of a named section
get_section_line() {
   local line=
   local cnt=`expr $(sed -n "/\[$1\]/{=;q;}" "$SETTING_PATH")`
   echo "$(sed -n "/\[$1\]/,/\[/p" "$SETTING_PATH" | grep -v "\[[A-Z]*[a-z]*\]")" | { 
   while read line; do
   #echo "rsl: $line cnt: $cnt 1: $1 2: $2 3: $3" >> debug
   cnt=`expr $cnt + 1`
   if [ -n "$2" ] && echo "$line" | grep -q "$2"; then
     echo "$line=$cnt"
     break;
   fi
   done
   }   
}

# Return last section line number or zero
get_section_last_line() { 
   local line=
   local cnt=$(sed -n "/\[$1\]/{=;q;}" "$SETTING_PATH")
   if [ -z "$cnt" ]; then
      cnt=0
   fi
   echo $(sed -n "/\[$1\]/,/\[/p" "$SETTING_PATH" | grep -v "\[[A-Z]*[a-z]*\]") | {
   while read line; do
      if [ "$cnt" -gt 0 ]; then
         cnt=`expr $cnt + 1`
      fi
   done
   echo "$cnt"
   }
}

# Handlers

# get file
on_settings() {
    utils_content_json
    #utils_is_action_authorized "${HTTP_COOKIE#token=}"
    if test -f ${SETTING_PATH}; then
       cnt=0
       body="{\"sections\":[{\"section\":"
       while read line; do
	 cnt=`expr $cnt + 1`
         if [ ! -z "${line}" ]; then
	    IFS="="; set -- $line
	    if [ ! -z "$1" ] && [ ! -z "$2" ]; then
               # settings
	       setting="${setting}{\"key\":\"${1}\", \"value\":\"${2}\", \"ln\": \"${cnt}\"},"
            elif [ ! -z "$1" ] && [ $cnt -gt 1 ]; then
               # sections
               setting="${setting%?}"
               body="${body}\"${section}\":[$setting],"
               section=$(echo "$1" | sed 's/[][]//g')
               setting=
            else
	        # first section
                section=$(echo "$1" | sed 's/[][]//g')
                body="${body}\"${section}\","
            fi
	 fi
	done < "$SETTING_PATH"
	setting="${setting%?}"
	echo "${body}\"${section}\":[$setting]}]}"
   else
      utils_print_error "Status: 404 Not Found" "Error: file: \"$SETTING_PATH\" not found."
   fi
}

# get line
on_line_read() {
  utils_content_json
  #utils_is_action_authorized "${HTTP_COOKIE#token=}"
  if test -f ${SETTING_PATH}; then
     section="$1" 
     line=$(get_section_line $1 $2)
     IFS="="; set -- $line
     if [ ! -z "$1" ] && [ ! -z "$2" ]; then
        setting="{\"key\": \"${1}\", \"value\": \"${2}\", \"line\": \"${3}\"}"
     else
        utils_print_error "Status: 500" "section \"$1\", line: \"$2\" does not exist."
     fi
     echo "{\"section\":\"${section}\",\"setting_list\":[$setting]}"
  else
     utils_print_error "Status: 404 Not Found" "Error: file: \"$SETTING_PATH\" not found."
  fi
}

# get section
on_section_read() {
  utils_content_json
  #utils_is_action_authorized "${HTTP_COOKIE#token=}"
  if test -f ${SETTING_PATH}; then
     section="$1" 
     cnt=$(sed -n "/\[$2\]/{=;q;}" "$SETTING_PATH")     
     echo $(sed -n "/\[$1\]/,/\[/p" "$SETTING_PATH" | grep -v "\[[A-Z]*[a-z]*\]") | { 
       while read line; do
          cnt=`expr $cnt + 1`
          IFS="="; set -- $line
          setting="${setting}{\"key\": \"${1}\", \"value\": \"${2}\", \"line\": \"${cnt}\"},"
       done 
       setting="${setting%?}"
       echo "{\"section\":\"${section}\",\"setting_list\":[$setting]}"
     }
  else
      utils_print_error "Status: 404 Not Found" "Error: file: \"$SETTING_PATH\" not found."
  fi
}

# new line 
on_line_post() {
   #utils_is_action_authorized "${HTTP_COOKIE:w#token=}"
   if test -f ${SETTING_PATH}; then
      setting="$1"
      json_str=$(echo "$POST_DATA" | ./json.sh -l) # parse post  
      IFS=","; set -- $(echo $json_str | head -1 | sed 's/\["\(.*\)"\]\t"\(.*\)"/\1,\2/') 
      json_str="{\"section\":\"${2}\",\"setting_list\":["
      pos=$(sed -n "/\[$2\]/{=;q;}" "$SETTING_PATH")
      section=$2
      if [ -n "$pos" ]; then # section exists 
         line=$(get_section_line "$section" "$setting")
         IFS="="; set -- $line
         if [ -z "$3" ]; then # after last line 
            pos=$(get_section_last_line "$section")
         fi
	 cnt=0
         echo $(echo "$POST_DATA" | ./json.sh -l | awk 'NR>1') | { while read setting; do 
            line=$(echo $setting | sed 's/^.*,"\([a-zA-Z]*\)"\]\t"\([a-zA-Z0-9]*\)"$/\1,\2/') 
            OIFS=$IFS;IFS=","; set -- $line
            case "$1" in 
               key) key=$2 ;;
             value) value=$2;;
            esac
            IFS=$OIFS
            cnt=`expr $cnt + 1`
            res=`expr $cnt % 3`
            if [ $res -eq 0 ]; then
              line=$(get_section_line "$section" "$key")
              if [ -z "$line" ]; then
                res=$(wc -l < "$SETTING_PATH")
                OIFS=$IFS;IFS=","; set -- $line
                if [ "$pos" -lt "$res" ]; then
                   pos=`expr $pos + 1`
                   json_str="${json_str}{\"key\":\"${key}\",\"value\":\"${value}\",\"line\":\"${pos}\"},"
		   sed -i "${pos}i ${key}=${value}" "$SETTING_PATH"
	        else
                  pos=`expr $pos + 1`
		  json_str="${json_str}{\"key\":\"${key}\",\"value\":\"${value}\",\"line\":\"${pos}\"},"
                  echo  "${key}=${value}" >> "$SETTING_PATH"
	        fi
                IFS=$OIFS
              else
                 utils_print_error "Status: 400 Bad Request" "Error: Line: \"$line\" already exists." 
              fi 
           fi
	 done
         utils_content_json
         echo "${json_str%,}]"
         }
      else
        utils_print_error "Status: 400 Bad Request" "Error: Section: \"$section\" does not exist."
      fi
   else  
      utils_print_error "Status: 404 Not Found" "Error: file: \"$SETTING_PATH\" not found."
   fi
}

# new section
on_section_post() {
   #utils_is_action_authorized "${HTTP_COOKIE#token=}"
   if test -f ${SETTING_PATH}; then
      section="$1"
      json_str=$(echo "$POST_DATA" | ./json.sh -l) # parse post  
      IFS=","; set -- $(echo $json_str | head -1 | sed 's/\["\(.*\)"\]\t"\(.*\)"/\1,\2/') 
      json_str="{\"section\":\"${2}\",\"setting_list\":["
      pos=$(sed -n "/\[$2\]/{=;q;}" "$SETTING_PATH")
      setting="$2"
      if [ -z "$pos" ]; then # not exists 
         pos=$(get_section_last_line "$section")
         lln=$(wc -l < "$SETTING_PATH")
         if [ "$pos" -lt "$lln" ] && [ "$pos" -ne 0 ]; then
            pos=`expr $pos + 1`
            sed -i "${pos}i \[${setting}\]" "$SETTING_PATH"
	 else
            pos=`expr $lln + 1`
	    echo "[${setting}]" >> "$SETTING_PATH"
	 fi
         utils_content_json
         echo "${json_str%,}]"
      else
         utils_print_error "Status: 400 Bad Request" "Error: Section: \"$setting\" already exists."
      fi
   else  
      utils_print_error "Status: 404 Not Found" "Error: file: \"$SETTING_PATH\" not found."
   fi
}

# Replace line 
on_line_put() {
  #UTILs_is_action_authorized "${HTTP_COOKIE#token=}"
  if test -f ${SETTING_PATH}; then
     json_str=$(echo "$POST_DATA" | ./json.sh -l) # parse post  
     IFS=","; set -- $(echo $json_str | head -1 | sed 's/\["\(.*\)"\]\t"\(.*\)"/\1,\2/') 
     json_str="{\"section\":\"${2}\",\"setting_list\":["
     pos=$(sed -n "/\[$2\]/{=;q;}" "$SETTING_PATH")
     section="$2"
echo "sect: $section 1: $1 2: $2" >> debug
     if [ -n "$1" ] && [ "${pos}" -gt 0 ]; then # section exists

        get_section_all ars "$setting"
        #delete_line_all ${ars[@]}
        lln=$(wc -l < $SETTING_PATH)
        utils_content_json
        echo "${section%?}]}"
     else
         utils_print_error "Status: 400 Bad Request" "Error: Section: \"$section\" does not exist."
     fi
  else
     utils_print_error "Status: 404 Not Found" "Error: file: \"$SETTING_PATH\" not found."
  fi
}  

# Delete line 
on_line_delete() {
  #UTILs_is_action_authorized "${HTTP_COOKIE#token=}"
  if test -f ${SETTING_PATH}; then
      setting=$(echo "$POST_DATA" | ./json.sh -l) # parse post  
      IFS=","; set -- $(echo "$setting" | head -1 | sed 's/\["\(.*\)"\]\t"\(.*\)"/\1,\2/') 
      json_str="{\"section\":\"${2}\",\"setting_list\":["
      pos=$(sed -n "/\[$2\]/{=;q;}" "$SETTING_PATH")
      section="$2"
      cnt=0
      if [ -n "$pos" ]; then # section exists
         echo $(echo "$setting" | awk 'NR>1') | { while read line; do
            cnt=`expr $cnt + 1`
            if [ `expr $cnt % 3` -eq 1 ]; then
               set -- $(echo $line | sed 's/^.* [0-9] "\([a-zA-Z]*\)"\]\t"\([a-zA-Z:0-9]*\)"$/\1,\2/') 
                  data="$data$2,"
            fi
         done
	 for key in ${data%,}; do
            line=$(get_section_line "$section" "$key")
            if [ -n "$line" ]; then
               OIFS=$IFS;IFS="="; set -- $line
               json_str="${json_str}{\"key\": \"${1}\", \"value\": \"${2}\", \"line\": \"${3}\"},"
               IFS=$OIFS
            fi
         done 
	 for key in ${data%,}; do
            line=$(get_section_line "$section" "$key")
            if [ -n "$line" ]; then
               OIFS=$IFS;IFS="="; set -- $line
               sed -i "${3}d" "${SETTING_PATH}"
               IFS=$OIFS
            else
               utils_print_error "Status: 400 Bad Request" "Error: key: \"$key\" does not exist."
            fi
         done
         utils_content_json
         echo "$json_str"
         }
      else
         utils_print_error "Status: 400 Bad Request" "Error: Section: \"$section\" does not exist."
      fi
  else
     utils_print_error "Status: 404 Not Found" "Error: file: \"$SETTING_PATH\" not found."
  fi
}

# Delete section 
on_section_delete() {
  #UTILs_is_action_authorized "${HTTP_COOKIE#token=
  if test -f ${SETTING_PATH}; then
      json_str=$(echo "$POST_DATA" | ./json.sh -l) # parse post  
      IFS=","; set -- $(echo $json_str | head -1 | sed 's/\["\(.*\)"\]\t"\(.*\)"/\1,\2/') 
      json_str="{\"section\":\"${2}\",\"setting_list\":["
      pos=$(sed -n "/\[$2\]/{=;q;}" "$SETTING_PATH")
      cnt=$pos
      section="$2"
      if [ -n "$pos" ]; then # section exists
         echo $(sed -n "/\[$section\]/,/\[/p" "$SETTING_PATH" | grep -v "\[[A-Z]*[a-z]*\]") | { 
         while read line; do
            cnt=`expr $cnt + 1`
            OIFS=$IFS;IFS="="; set -- $line
            json_str="${json_str}{\"key\": \"${1}\", \"value\": \"${2}\", \"line\": \"${cnt}\"},"
            IFS=$OIFS
         done 
         sed -i "${pos},${cnt}d" "${SETTING_PATH}" 
         utils_content_json
         echo "${json_str%,}]"
         } 
      else
         utils_print_error "Status: 400 Bad Request" "Error: Section: \"$section\" does not exist."
      fi
  else
     utils_print_error "Status: 404 Not Found" "Error: file: \"$SETTING_PATH\" not found."
  fi
}

echo "qs: $QUERY_STRING" > debug
echo "req: $REQUEST_METHOD" >> debug

# Parse Request
if [ -z $QUERY_STRING ]; then
   on_settings
else
    IFS="&"
    set -- $QUERY_STRING
    key="${1%=*}"
    if [ "$REQUEST_METHOD" = "GET" ]; then
       if [ ${key} = "section" -a "${2%=*}" = "line" ]; then
	  on_line_read "${1#*=}" "${2#*=}" 
       elif [ ${key} = "section" ]; then
          on_section_read "${1#*=}"
       else
          utils_print_error "Status: 421 Misdirected Request" "Use only line, section or null."
       fi
    elif [ "$REQUEST_METHOD" = "POST" ]; then
       if [ "$CONTENT_LENGTH" -gt 0 ] && [ -z "${CONTENT_TYPE##*"application/json"*}" ]; then
          POST_DATA=`cat /dev/stdin`
          case ${key} in
          put)
              if [ ${1#*=} = "line" ]; then
                 on_line_put 
              elif [ ${1#*=} = "section" ]; then
                 on_section_put 
              else
                 utils_print_error "Status: 421 Misdirected Request" "Use only line, section or file."
              fi
            ;;
          post)
	     if [ ${1#*=} = "line" ]; then
                on_line_post "${2#*=}" 
	     elif [ ${1#*=} = "section" ]; then
                on_section_post "${2#*=}"
             else
               utils_print_error "Status: 421 Misdirected Request" "Use only line, section or null."
             fi
            ;;
          patch)
              if [ ${1#*=} = "line" ]; then
                 on_line_patch 
              else
                 utils_print_error "Status: 421 Misdirected Request" "Use only line"
              fi
            ;;
          delete)
              if [ ${1#*=} = "line" ]; then
                 on_line_delete
              elif [ ${1#*=} = "section" ]; then
                 on_section_delete
              else
                 utils_print_error "Status: 421 Misdirected Request" "Use only line."
              fi
            ;;
          *)
              utils_print_error "Status: 421 Misdirected Request" "Use only put, post, patch, delete."
           ;;
         esac
       else
          utils_print_error "Status: 501 Not Implemented" "Only application/json excepted."
       fi
    else
       utils_print_error "Status: 501 Not Implemented" "Method is not recognized. Use only GET or POST."
    fi
fi

